# Generated by Django 3.0.2 on 2020-01-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Identification',
        ),
    ]
