version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Chatapp_project/
permissions:
  - object: /home/ubuntu/Chatapp_project/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependancies.sh
      timeout: 600
      runas: ubuntu
    - location: scripts/gunicorn.sh
      timeout: 600
      runas: ubuntu
    - location: scripts/nginx.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: ubuntu
